language: node_js

node_js:
  - 10.8

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info
    
jobs:
  include:
    - stage: smoke
      script:
        - npm run start:ci &
        - npm run smoke
    - stage: site
       script:
        - npm run start:ci &
        - npm run site
    - stage: management
       script:
        - npm run start:ci &
        - npm run management

