language: node_js

node_js:
  - 10.8

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info
    
jobs:
  include:
    - stage: smoke-site
      script:
        - npm run start:ci &
        - npm run smoke-site
        - kill $(jobs -p) || true
    - stage: smoke-management
      script:
        - npm run start:ci &
        - npm run smoke-management
        - kill $(jobs -p) || true        
    - stage: site
      script:
        - npm run start:ci &
        - npm run site
        - kill $(jobs -p) || true
    - stage: management
      script:
        - npm run start:ci &
        - npm run management
        - kill $(jobs -p) || true        


