language: node_js

node_js:
  - 10.8

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info

defaults: &smoke
  script:
    - $(npm bin)/print-env TRAVIS
    - npm run start:ci &
    - npm run smoke
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME="smoke chrome on Travis CI"
      <<: *smoke
